{{- if .Values.argocd.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.argocd.rbac.clusterRoleBindingName }}
  labels:
    {{- include "employment-management.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.argocd.rbac.serviceAccountName }}
    namespace: {{ .Values.argocd.rbac.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.argocd.rbac.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}