{{- if .Values.argocd.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.argocd.rbac.serviceAccountName }}
  namespace: {{ .Values.argocd.rbac.namespace }}
  labels:
    {{- include "employment-management.labels" . | nindent 4 }}
{{- end }}