apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: argocd-server-healthcheck
  namespace: {{ .Release.Namespace }}
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        portSpecification: USE_FIXED_PORT
        requestPath: /argocd/
  targetRef:
    group: ""
    kind: Service
    name: argocd-server