{{- if .Values.argocd.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: employment-management-argocd-controller-impersonator
  labels:
    {{- include "employment-management.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - impersonate
{{- end }}