apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "employment-management.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "employment-management.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      {{- include "employment-management.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "employment-management.selectorLabels" . | nindent 8 }}

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: employment-management
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          env:
            - name: POSTGRES_HOST
              value: {{ include "employment-management.postgresName" . | quote }}

            - name: POSTGRES_PORT
              value: {{ .Values.postgres.port | quote }}

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "employment-management.postgresName" . }}
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "employment-management.postgresName" . }}
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "employment-management.postgresName" . }}
                  key: POSTGRES_PASSWORD

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL

          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}

          startupProbe:
            httpGet:
              path: /api/employees
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /api/employees
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /api/employees
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3