apiVersion: v1
kind: Service
metadata:
  name: {{ include "employment-management.postgresName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "employment-management.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "employment-management.postgresName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}