{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-route" .Release.Name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "employment-management.labels" . | nindent 4 }}
spec:
  hostnames:
    - {{ .Values.gateway.hostname | quote }}

  parentRefs:
    - name: {{ printf "%s-gateway" .Release.Name | trunc 63 | trimSuffix "-" }}
      kind: Gateway
      group: gateway.networking.k8s.io
      sectionName: https

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      backendRefs:
        - name: {{ include "employment-management.fullname" . }}
          port: {{ .Values.app.service.port }}
{{- end }}