{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    {{- include "employment-management.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.port }}
      protocol: TCP
{{- end }}