{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: employment-management-role
  namespace: stateful-demo
  labels:
    app.kubernetes.io/name: employment-management
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - replicasets
    verbs:
      - get
      - list
      - watch
{{- end }}