{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "employment-management.serviceAccountName" . }}
  labels:
    {{- include "employment-management.labels" . | nindent 4 }}
{{- end }}