{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: stateful-demo
  labels:
    app.kubernetes.io/name: employment-management
    app.kubernetes.io/managed-by: Helm
{{- end }}