apiVersion: v1
kind: Service
metadata:
  name: {{ include "employment-management.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "employment-management.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    {{- include "employment-management.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: 8080
      protocol: TCP