apiVersion: gateway.networking.k8s.io/v1
kind: Gateway

metadata:
  name: employment-management-gateway
  namespace: stateful-demo

spec:
  gatewayClassName: gke-l7-global-external-managed

  addresses:
    - type: NamedAddress
      value: cloudaiops-gateway-ip

  listeners:
    - name: https
      protocol: HTTPS
      port: 443

      tls:
        mode: Terminate
        certificateRefs:
          - name: cloudaiops-tls
            kind: Secret

      allowedRoutes:
        namespaces:
          from: Same